CREATE TABLE paises (
    codigo CHAR(2) PRIMARY KEY,
    nombre VARCHAR2(40),
    poblacion NUMBER (10)
);

CREATE TABLE ciudades (
    codigo NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(30),
    poblacion NUMBER(10),
    codigoPais CHAR(2)
);

INSERT INTO paises (codigo, nombre, poblacion) VALUES ('US', 'Estados Unidos', 331002651);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('CN', 'China', 1439323776);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('IN', 'India', 1380004385);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('ID', 'Indonesia', 273523615);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('PK', 'Pakistán', 220892340);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('BR', 'Brasil', 212559417);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('NG', 'Nigeria', 206139589);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('BD', 'Bangladés', 164689383);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('RU', 'Rusia', 145934462);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('MX', 'México', 128932753);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('JP', 'Japón', 126476461);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('ET', 'Etiopía', 114963588);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('PH', 'Filipinas', 109581078);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('EG', 'Egipto', 102334404);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('VN', 'Vietnam', 97338579);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('CD', 'República Democrática del Congo', 89561403);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('TR', 'Turquía', 84339067);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('IR', 'Irán', 83992949);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('DE', 'Alemania', 83783942);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('TH', 'Tailandia', 69799978);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('GB', 'Reino Unido', 67886011);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('FR', 'Francia', 65273511);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('IT', 'Italia', 60461826);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('TZ', 'Tanzania', 59734218);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('ZA', 'Sudáfrica', 59308690);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('MM', 'Birmania', 54409800);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('KE', 'Kenia', 53771296);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('KR', 'Corea del Sur', 51269185);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('CO', 'Colombia', 50882891);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('ES', 'España', 46754778);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('UG', 'Uganda', 45741007);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('AR', 'Argentina', 45195774);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('DZ', 'Argelia', 43851044);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('SD', 'Sudán', 43849260);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('UA', 'Ucrania', 43733762);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('IQ', 'Irak', 40222493);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('AF', 'Afganistán', 38928346);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('PL', 'Polonia', 38386000);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('CA', 'Canadá', 37742154);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('MA', 'Marruecos', 36910560);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('SA', 'Arabia Saudita', 34813871);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('UZ', 'Uzbekistán', 33469203);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('PE', 'Perú', 32971854);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('MY', 'Malasia', 32365999);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('AO', 'Angola', 32866272);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('GH', 'Ghana', 31072940);
INSERT INTO paises (codigo, nombre, poblacion) VALUES ('MZ', 'Mozambique', 31255435);

INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (1, 'Tokio', 37393128, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (2, 'Delhi', 30290936, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (3, 'Shanghái', 27058479, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (4, 'São Paulo', 22043028, 'BR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (5, 'Ciudad de México', 21782378, 'MX');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (6, 'El Cairo', 20484965, 'EG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (7, 'Dhaka', 20283552, 'BD');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (8, 'Bombay', 20185064, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (9, 'Pekín', 20035455, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (10, 'Osaka', 19222665, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (11, 'Nueva York', 18804000, 'US');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (12, 'Karachi', 16459400, 'PK');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (13, 'Chongqing', 16382376, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (14, 'Estambul', 15462452, 'TR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (15, 'Buenos Aires', 15100000, 'AR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (16, 'Kolkata', 14850000, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (17, 'Lagos', 14200000, 'NG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (18, 'Kinshasa', 13800000, 'CD');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (19, 'Manila', 13600000, 'PH');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (20, 'Tianjin', 13245000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (21, 'Guangzhou', 13080500, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (22, 'Río de Janeiro', 13000000, 'BR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (23, 'Lahore', 12188000, 'PK');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (24, 'Bangalore', 12000000, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (25, 'Shenzhen', 11908400, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (26, 'Moscú', 11920000, 'RU');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (27, 'Chennai', 11324000, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (28, 'Bogotá', 11100000, 'CO');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (29, 'París', 11020000, 'FR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (30, 'Lima', 10900000, 'PE');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (31, 'Bangkok', 10539000, 'TH');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (32, 'Londres', 10400000, 'GB');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (33, 'Chengdu', 10300000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (34, 'Nagoya', 10200000, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (35, 'Teherán', 10100000, 'IR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (36, 'Ho Chi Minh', 9000000, 'VN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (37, 'Luanda', 8900000, 'AO');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (38, 'Wuhan', 8800000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (39, 'Ahmedabad', 8700000, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (40, 'Kuala Lumpur', 8500000, 'MY');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (41, 'Hong Kong', 8400000, 'HK');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (42, 'Hyderabad', 8300000, 'IN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (43, 'Hangzhou', 8200000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (44, 'Riyadh', 8100000, 'SA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (45, 'Bagdad', 8000000, 'IQ');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (46, 'Santiago', 7900000, 'CL');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (47, 'Toronto', 7800000, 'CA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (48, 'Singapur', 7700000, 'SG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (49, 'Shijiazhuang', 7600000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (50, 'Sydney', 7500000, 'AU');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (51, 'Surabaya', 7400000, 'ID');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (52, 'Yangon', 7300000, 'MM');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (53, 'Alexandría', 7200000, 'EG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (54, 'Abiyán', 7100000, 'CI');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (55, 'Los Ángeles', 7000000, 'US');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (56, 'Yokohama', 6900000, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (57, 'Busan', 6800000, 'KR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (58, 'Hangzhou', 6700000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (59, 'Riyadh', 6600000, 'SA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (60, 'Bagdad', 6500000, 'IQ');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (61, 'Santiago', 6400000, 'CL');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (62, 'Toronto', 6300000, 'CA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (63, 'Singapur', 6200000, 'SG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (64, 'Shijiazhuang', 6100000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (65, 'Sydney', 6000000, 'AU');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (66, 'Surabaya', 5900000, 'ID');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (67, 'Yangon', 5800000, 'MM');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (68, 'Alexandría', 5700000, 'EG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (69, 'Abiyán', 5600000, 'CI');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (70, 'Los Ángeles', 5500000, 'US');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (71, 'Yokohama', 5400000, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (72, 'Busan', 5300000, 'KR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (73, 'Hangzhou', 5200000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (74, 'Riyadh', 5100000, 'SA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (75, 'Bagdad', 5000000, 'IQ');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (76, 'Santiago', 4900000, 'CL');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (77, 'Toronto', 4800000, 'CA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (78, 'Singapur', 4700000, 'SG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (79, 'Shijiazhuang', 4600000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (80, 'Sydney', 4500000, 'AU');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (81, 'Surabaya', 4400000, 'ID');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (82, 'Yangon', 4300000, 'MM');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (83, 'Alexandría', 4200000, 'EG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (84, 'Abiyán', 4100000, 'CI');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (85, 'Los Ángeles', 4000000, 'US');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (86, 'Yokohama', 3900000, 'JP');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (87, 'Busan', 3800000, 'KR');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (88, 'Hangzhou', 3700000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (89, 'Riyadh', 3600000, 'SA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (90, 'Bagdad', 3500000, 'IQ');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (91, 'Santiago', 3400000, 'CL');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (92, 'Toronto', 3300000, 'CA');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (93, 'Singapur', 3200000, 'SG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (94, 'Shijiazhuang', 3100000, 'CN');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (95, 'Sydney', 3000000, 'AU');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (96, 'Surabaya', 2900000, 'ID');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (97, 'Yangon', 2800000, 'MM');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (98, 'Alexandría', 2700000, 'EG');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (99, 'Abiyán', 2600000, 'CI');
INSERT INTO ciudades (codigo, nombre, poblacion, codigoPais) VALUES (100, 'Los Ángeles', 2500000, 'US');
